apiVersion: v1
kind: Secret
metadata:
  name: admin-service-secret
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.secrets.INTERNAL_SERVICE_TOKEN }}