apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: admin-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP