apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secret
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}
  JWT_SECRET_KEY: {{ .Values.secrets.JWT_SECRET_KEY }}
  INTERNAL_SERVICE_TOKEN: {{ .Values.secrets.INTERNAL_SERVICE_TOKEN }}