apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
  namespace: chillmadi-ns
type: Opaque
stringData:
  JWT_SECRET: "{{ .Values.env.JWT_SECRET }}"
  INTERNAL_SERVICE_TOKEN: "{{ .Values.env.INTERNAL_SERVICE_TOKEN }}"
  MONGODB_URI: "{{ .Values.env.MONGODB_URI }}"